services:
  django:
    image: ds_judgments_public_ui_django
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app:z
      - ../ds-caselaw-custom-api-client:/apiclient
    init: true
    environment:
      DATABASE_URL: "postgres://postgres:admin@postgres:5432/ds_judgements_public_ui"
      DJANGO_SETTINGS_MODULE: "config.settings.local"
      SECRET_KEY: local_dev_secret_key
      SECURE_SSL_REDIRECT: "false"
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    # do nothing forever - exec commands elsewhere
    command: tail -f /dev/null

  postgres:
    image: postgres:15.14@sha256:1cd9dd548427751dc0fabb24a3bdf96a6dd08c0025a167ecbb5c14bec21ff94c
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ds_judgements_public_ui
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      PGDATABASE: ds_judgements_public_ui
      PGUSER: postgres
      PGPASSWORD: admin
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./database_backups:/backups:z

  docs:
    image: ds_judgements_public_ui_local_docs
    container_name: ds_judgements_public_ui_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./ds_judgements_public_ui:/app/ds_judgements_public_ui:z
    ports:
      - "7000:7000"
    command: /start-docs

  e2e_tests:
    container_name: e2e_tests_container
    build:
      context: ./e2e_tests
      dockerfile: "../compose/local/e2e_tests/Dockerfile"

    profiles: [e2e_tests]
    volumes:
      - "./e2e_tests:/app:z"
    tty: true

networks:
  default:
    name: caselaw
    external: true
